port: 1234
endpoints:
    - request:
        path: /api/v1/todos/
        method: GET
      response:
        code: 200
        body: todos.json
        headers:
            content-type: text/json

    - request:
        path: /api/v1/user/*/
        method: GET
      response:
        code: 200
        body: user.json
        headers:
            content-type: text/json

    - request:
        path: /api/v1/user/*/name/
        method: GET
      response:
        code: 200
        body: user_name.json
        headers:
            content-type: text/json

    - request:
        path: /api/v1/users?id=1234
        method: GET
      response:
        code: 200
        body: user2.json
        headers:
            content-type: text/json

    - request:
        path: /api/v1/items?id=*
        method: GET
      response:
        code: 200
        body: user.json
        headers:
            content-type: text/json
